[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
exclude = scripts/

[mypy-firebase_admin.*]
ignore_missing_imports = True

[mypy-flask_swagger_ui.*]
ignore_missing_imports = True
